"""initial schema: users, sessions, traveller profiles

Revision ID: 108420df661f
Revises:
Create Date: 2026-08-13 12:03:20.847801
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "108420df661f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("role", sa.Enum("USER", "ADMIN", name="role"), nullable=False),
        sa.Column("telegram_user_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_users_telegram_user_id")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "traveller_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("passport_countries", sa.ARRAY(sa.String(length=2)), nullable=False),
        sa.Column("residence_country", sa.String(length=2), nullable=True),
        sa.Column("home_airports", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preferred_airports", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preferred_airlines", sa.ARRAY(sa.String(length=3)), nullable=False),
        sa.Column("preferred_alliances", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("excluded_airlines", sa.ARRAY(sa.String(length=3)), nullable=False),
        sa.Column("preferred_cabins", sa.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("maximum_stops", sa.Integer(), nullable=True),
        sa.Column("maximum_trip_duration_days", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "cardinality(passport_countries) >= 1",
            name=op.f("ck_traveller_profiles_has_at_least_one_passport"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_traveller_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_traveller_profiles")),
    )
    op.create_index(
        op.f("ix_traveller_profiles_user_id"), "traveller_profiles", ["user_id"], unique=False
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "traveller_relationships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("traveller_id", sa.UUID(), nullable=False),
        sa.Column("companion_id", sa.UUID(), nullable=False),
        sa.Column(
            "points_relationship",
            sa.Enum(
                "INDIVIDUALLY_USABLE",
                "TRANSFERABLE",
                "SHAREABLE",
                "NOT_COMBINABLE",
                name="pointsrelationship",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "traveller_id != companion_id",
            name=op.f("ck_traveller_relationships_companion_is_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["companion_id"],
            ["traveller_profiles.id"],
            name=op.f("fk_traveller_relationships_companion_id_traveller_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["traveller_id"],
            ["traveller_profiles.id"],
            name=op.f("fk_traveller_relationships_traveller_id_traveller_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_traveller_relationships")),
    )
    op.create_index(
        op.f("ix_traveller_relationships_companion_id"),
        "traveller_relationships",
        ["companion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_traveller_relationships_traveller_id"),
        "traveller_relationships",
        ["traveller_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_traveller_relationships_traveller_id"), table_name="traveller_relationships"
    )
    op.drop_index(
        op.f("ix_traveller_relationships_companion_id"), table_name="traveller_relationships"
    )
    op.drop_table("traveller_relationships")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_traveller_profiles_user_id"), table_name="traveller_profiles")
    op.drop_table("traveller_profiles")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###

    # Alembic's autogenerate drops the tables that reference these native Postgres
    # ENUM types but not the types themselves, which left them behind and made a
    # repeat upgrade fail with "type already exists". Verified against a live
    # Postgres 17 round-trip (spec CLAUDE.md §5, "Testing").
    sa.Enum(name="pointsrelationship").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="role").drop(op.get_bind(), checkfirst=True)
