"""rewrite cash_observations to spec 56 shape

Revision ID: 3f8c10c6e28a
Revises: 70d85219ea17
Create Date: 2026-08-13 20:09:32.533061
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3f8c10c6e28a"
down_revision: str | None = "70d85219ea17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cash_observations", sa.Column("origin", sa.String(length=4), nullable=False))
    op.add_column(
        "cash_observations", sa.Column("destination", sa.String(length=4), nullable=False)
    )
    op.add_column(
        "cash_observations", sa.Column("depart_month", sa.String(length=7), nullable=False)
    )
    op.add_column(
        "cash_observations", sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column(
        "cash_observations", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column("cash_observations", sa.Column("poll_count", sa.Integer(), nullable=False))
    op.add_column("cash_observations", sa.Column("last_search_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_cash_observations_itinerary_id"),
        "cash_observations",
        ["itinerary_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cash_observations_source"), "cash_observations", ["source"], unique=False
    )
    op.drop_constraint(
        op.f("fk_cash_observations_search_id_searches"), "cash_observations", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_cash_observations_last_search_id_searches"),
        "cash_observations",
        "searches",
        ["last_search_id"],
        ["id"],
    )
    op.drop_column("cash_observations", "retrieved_at")
    op.drop_column("cash_observations", "search_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cash_observations", sa.Column("search_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "cash_observations",
        sa.Column(
            "retrieved_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_cash_observations_last_search_id_searches"),
        "cash_observations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_cash_observations_search_id_searches"),
        "cash_observations",
        "searches",
        ["search_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_cash_observations_source"), table_name="cash_observations")
    op.drop_index(op.f("ix_cash_observations_itinerary_id"), table_name="cash_observations")
    op.drop_column("cash_observations", "last_search_id")
    op.drop_column("cash_observations", "poll_count")
    op.drop_column("cash_observations", "last_seen_at")
    op.drop_column("cash_observations", "first_seen_at")
    op.drop_column("cash_observations", "depart_month")
    op.drop_column("cash_observations", "destination")
    op.drop_column("cash_observations", "origin")
    # ### end Alembic commands ###
