"""add raw payload retention

Revision ID: 5c44068e84aa
Revises: 93b84082fc41
Create Date: 2026-08-13 19:44:23.343927
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5c44068e84aa"
down_revision: str | None = "93b84082fc41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_payloads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("request_key", sa.String(length=256), nullable=False),
        sa.Column("content_encoding", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.LargeBinary(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_payloads")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raw_payloads")
    # ### end Alembic commands ###
