"""add flight price daily aggregates

Revision ID: 626a8968de65
Revises: 3f8c10c6e28a
Create Date: 2026-08-13 20:38:12.104074
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "626a8968de65"
down_revision: str | None = "3f8c10c6e28a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flight_price_daily",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("aggregate_date", sa.Date(), nullable=False),
        sa.Column("route", sa.String(length=9), nullable=False),
        sa.Column("cabin", sa.String(length=32), nullable=False),
        sa.Column("fare_family", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("minimum_price_minor", sa.Integer(), nullable=False),
        sa.Column("median_price_minor", sa.Integer(), nullable=False),
        sa.Column("maximum_price_minor", sa.Integer(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flight_price_daily")),
        sa.UniqueConstraint(
            "aggregate_date",
            "route",
            "cabin",
            "fare_family",
            "source",
            "currency",
            name="uq_flight_price_daily_key",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flight_price_daily")
    # ### end Alembic commands ###
