"""add fx rates table

Revision ID: 75094539199b
Revises: dd16f5f8efd7
Create Date: 2026-08-13 15:12:44.383858
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "75094539199b"
down_revision: str | None = "dd16f5f8efd7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fx_rates",
        sa.Column("quote_currency", sa.String(length=3), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), server_default="EUR", nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("source", sa.String(length=64), server_default="ecb", nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("quote_currency", "rate_date", name=op.f("pk_fx_rates")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fx_rates")
    # ### end Alembic commands ###
