"""partition cash_observations and raw_payloads by month

Revision ID: 7fa84f663103
Revises: 626a8968de65
Create Date: 2026-08-13 20:47:42.356810

Hand-written, not autogenerated: Alembic's autogenerate does not detect
`postgresql_partition_by` changes at all (a bare diff against these models
produces an empty upgrade/downgrade — confirmed running it for real before
writing this by hand, not assumed). Postgres also cannot ALTER an existing
ordinary table into a partitioned one, so both tables are dropped and
recreated as partitioned parents with the same columns spec §55 already
established, plus initial bootstrap partitions so inserts work immediately
after this migration without waiting for the maintenance job's own monthly
schedule (apps/worker/jobs/maintain_partitions.py) to run.

Pre-production (CLAUDE.md's stated current project state: no deployment
exists yet), so dropping and recreating loses no real data — the same
posture already taken by every prior migration that reshaped these tables.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7fa84f663103"
down_revision: str | None = "626a8968de65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Bootstrap window: covers the current development period with margin.
# apps/worker/jobs/maintain_partitions.py keeps a 3-month rolling window
# going forward from whatever "now" actually is at deploy time — this list
# only needs to get a fresh install past its first maintenance run.
_BOOTSTRAP_MONTHS: list[tuple[int, int]] = [
    (2026, 8),
    (2026, 9),
    (2026, 10),
    (2026, 11),
    (2026, 12),
    (2027, 1),
    (2027, 2),
]


def _month_bounds(year: int, month: int) -> tuple[str, str]:
    lower = f"{year:04d}-{month:02d}-01"
    upper = f"{year + 1:04d}-01-01" if month == 12 else f"{year:04d}-{month + 1:02d}-01"
    return lower, upper


def _create_bootstrap_partitions(table: str) -> None:
    for year, month in _BOOTSTRAP_MONTHS:
        lower, upper = _month_bounds(year, month)
        op.execute(
            f'CREATE TABLE "{table}_p{year:04d}_{month:02d}" '
            f"PARTITION OF \"{table}\" FOR VALUES FROM ('{lower}') TO ('{upper}')"
        )


def upgrade() -> None:
    op.drop_table("cash_observations")
    op.create_table(
        "cash_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("itinerary_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("origin", sa.String(length=4), nullable=False),
        sa.Column("destination", sa.String(length=4), nullable=False),
        sa.Column("depart_month", sa.String(length=7), nullable=False),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("freshness", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("offer", sa.JSON(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("poll_count", sa.Integer(), nullable=False),
        sa.Column("last_search_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_search_id"],
            ["searches.id"],
            name=op.f("fk_cash_observations_last_search_id_searches"),
        ),
        sa.PrimaryKeyConstraint("id", "first_seen_at", name=op.f("pk_cash_observations")),
        postgresql_partition_by="RANGE (first_seen_at)",
    )
    op.create_index(
        op.f("ix_cash_observations_itinerary_id"),
        "cash_observations",
        ["itinerary_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cash_observations_source"), "cash_observations", ["source"], unique=False
    )
    _create_bootstrap_partitions("cash_observations")

    op.drop_table("raw_payloads")
    op.create_table(
        "raw_payloads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("request_key", sa.String(length=256), nullable=False),
        sa.Column("content_encoding", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.LargeBinary(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", "retrieved_at", name=op.f("pk_raw_payloads")),
        postgresql_partition_by="RANGE (retrieved_at)",
    )
    _create_bootstrap_partitions("raw_payloads")


def downgrade() -> None:
    op.drop_table("raw_payloads")
    op.create_table(
        "raw_payloads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("request_key", sa.String(length=256), nullable=False),
        sa.Column("content_encoding", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.LargeBinary(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_payloads")),
    )

    op.drop_table("cash_observations")
    op.create_table(
        "cash_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("itinerary_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("origin", sa.String(length=4), nullable=False),
        sa.Column("destination", sa.String(length=4), nullable=False),
        sa.Column("depart_month", sa.String(length=7), nullable=False),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("freshness", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("offer", sa.JSON(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("poll_count", sa.Integer(), nullable=False),
        sa.Column("last_search_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_search_id"],
            ["searches.id"],
            name=op.f("fk_cash_observations_last_search_id_searches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_observations")),
    )
    op.create_index(
        op.f("ix_cash_observations_itinerary_id"),
        "cash_observations",
        ["itinerary_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cash_observations_source"), "cash_observations", ["source"], unique=False
    )
