"""add searches and cash observations

Revision ID: 93b84082fc41
Revises: 75094539199b
Create Date: 2026-08-13 17:27:22.459974
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "93b84082fc41"
down_revision: str | None = "75094539199b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "searches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("origin", sa.String(length=4), nullable=False),
        sa.Column("destination", sa.String(length=4), nullable=False),
        sa.Column("depart_month", sa.String(length=7), nullable=False),
        sa.Column(
            "state",
            sa.Enum("PENDING", "RUNNING", "READY", "FAILED", name="searchstate"),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_searches_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_searches")),
    )
    op.create_table(
        "cash_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("search_id", sa.UUID(), nullable=False),
        sa.Column("itinerary_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("freshness", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("offer", sa.JSON(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["search_id"], ["searches.id"], name=op.f("fk_cash_observations_search_id_searches")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_observations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cash_observations")
    op.drop_table("searches")
    # ### end Alembic commands ###
    # Alembic drops the table but never the Postgres ENUM type backing
    # `state` — recurring gotcha in this project (see 108420df661f,
    # b319bcb648e2). Left behind, it breaks the *next* upgrade attempt with
    # "type searchstate already exists".
    sa.Enum(name="searchstate").drop(op.get_bind(), checkfirst=True)
