"""add reference data: airports, airlines, airport groups

Revision ID: b319bcb648e2
Revises: dd16f5f8efd7
Create Date: 2026-08-13 14:30:08.815572
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b319bcb648e2"
down_revision: str | None = "dd16f5f8efd7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airlines",
        sa.Column("icao_code", sa.String(length=3), nullable=False),
        sa.Column("iata_code", sa.String(length=2), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("active_in_source", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("icao_code", name=op.f("pk_airlines")),
    )
    op.create_index(op.f("ix_airlines_iata_code"), "airlines", ["iata_code"], unique=False)
    op.create_table(
        "airports",
        sa.Column("icao_code", sa.String(length=4), nullable=False),
        sa.Column("iata_code", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("airport_type", sa.String(length=32), nullable=False),
        sa.Column("municipality", sa.String(length=128), nullable=False),
        sa.Column("iso_country", sa.String(length=2), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column(
            "timezone_resolution",
            sa.Enum("OPENFLIGHTS", "COORDINATES", "UNRESOLVED", name="timezoneresolution"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("icao_code", name=op.f("pk_airports")),
    )
    op.create_index(op.f("ix_airports_iata_code"), "airports", ["iata_code"], unique=True)
    op.create_index(op.f("ix_airports_iso_country"), "airports", ["iso_country"], unique=False)
    op.create_table(
        "airport_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("anchor_icao_code", sa.String(length=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["anchor_icao_code"],
            ["airports.icao_code"],
            name=op.f("fk_airport_groups_anchor_icao_code_airports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_airport_groups")),
    )
    op.create_table(
        "airport_group_members",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("airport_icao_code", sa.String(length=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["airport_icao_code"],
            ["airports.icao_code"],
            name=op.f("fk_airport_group_members_airport_icao_code_airports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["airport_groups.id"],
            name=op.f("fk_airport_group_members_group_id_airport_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "group_id", "airport_icao_code", name=op.f("pk_airport_group_members")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("airport_group_members")
    op.drop_table("airport_groups")
    op.drop_index(op.f("ix_airports_iso_country"), table_name="airports")
    op.drop_index(op.f("ix_airports_iata_code"), table_name="airports")
    op.drop_table("airports")
    op.drop_index(op.f("ix_airlines_iata_code"), table_name="airlines")
    op.drop_table("airlines")
    # ### end Alembic commands ###

    # Same gap as 108420df661f: autogenerate drops the tables referencing
    # this native Postgres ENUM type but not the type itself, which fails a
    # repeat upgrade with "type already exists". Verified against a live
    # Postgres 17 round-trip.
    sa.Enum(name="timezoneresolution").drop(op.get_bind(), checkfirst=True)
