"""add unique constraint on companion pairs

Revision ID: dd16f5f8efd7
Revises: 108420df661f
Create Date: 2026-08-13 14:00:48.977764
"""

from collections.abc import Sequence

from alembic import op

revision: str = "dd16f5f8efd7"
down_revision: str | None = "108420df661f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_traveller_companion_pair", "traveller_relationships", ["traveller_id", "companion_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_traveller_companion_pair", "traveller_relationships", type_="unique")
    # ### end Alembic commands ###
